type allergen {
    id: ID!,
    name: string!
}

type foodItem {
    id: ID!,
    name: string!,
    allergens: [allergen!],
    ingredients: [foodItem!]
}

type meal {
    id: ID!,
    time: DateTime!,
    foodItems: [foodItem!],
}